Repository ShinhanT3-CardProject/Backend_repo, pull requests merged in 2024-09, with the labels that each got.

#92 [Fix] contribution 업데이트 로직 변경
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
Labels: 🛠️fix

#106 [CI/CDTest] Update pom.xml
  pom.xml
Labels: 💯test

#107 [Fix] 테마 구조 수정
  src/main/java/com/shinhan/soloplay/card/CardController.java
  src/main/java/com/shinhan/soloplay/coupon/CouponController.java
  src/main/java/com/shinhan/soloplay/coupon/CouponServiceImpl.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryDTO.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryEntity.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryRepository.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryService.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryServiceImpl.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantDTO.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
  src/main/java/com/shinhan/soloplay/openAI/OpenAIController.java
  src/main/java/com/shinhan/soloplay/openAI/OpenAIService.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
  src/main/java/com/shinhan/soloplay/subcategory/SubCategoriesDTO.java
  src/main/java/com/shinhan/soloplay/subcategory/SubCategoryDTO.java
  src/main/java/com/shinhan/soloplay/subcategory/SubCategoryEntity.java
  src/main/java/com/shinhan/soloplay/subcategory/SubCategoryRepository.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeControllerJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeDetailResponseDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRegisterDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeSearchDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImplJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentDTO.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentEntity.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentRepository.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentsResponseDTO.java
  src/test/java/com/shinhan/soloplay/ThemeTest.java
Labels: 🛠️fix

#108 🌟(#8 ) [Feat] 테마 조회 페이징 구현
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl.java
Labels: 🌟feature

#110 [Bugfix] 쿼리 중복 조회 제거
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository.java
Labels: 🐞bugfix

#111 🌟[Feat] Deploy Main Update
  README.md
  src/main/java/com/shinhan/soloplay/card/CardController.java
  src/main/java/com/shinhan/soloplay/config/WebConfig.java
  src/main/java/com/shinhan/soloplay/coupon/CouponController.java
  src/main/java/com/shinhan/soloplay/coupon/CouponServiceImpl.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryDTO.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryEntity.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryRepository.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryService.java
  src/main/java/com/shinhan/soloplay/maincategory/MainCategoryServiceImpl.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantDTO.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
  src/main/java/com/shinhan/soloplay/openAI/OpenAIController.java
  src/main/java/com/shinhan/soloplay/openAI/OpenAIService.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
  src/main/java/com/shinhan/soloplay/subcategory/SubCategoriesDTO.java
  src/main/java/com/shinhan/soloplay/subcategory/SubCategoryDTO.java
  src/main/java/com/shinhan/soloplay/subcategory/SubCategoryEntity.java
  src/main/java/com/shinhan/soloplay/subcategory/SubCategoryRepository.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeControllerJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeDetailResponseDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRegisterDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeSearchDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImplJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentDTO.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentEntity.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentRepository.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentsResponseDTO.java
  src/test/java/com/shinhan/soloplay/ThemeTest.java
Labels: 🌟feature

#113 [Bugfix] 포인트 수여 조건 추가
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
Labels: 🐞bugfix

#115 🌟(#4) [Fix] 포인트 수정 추가
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentsResponseDTO.java
Labels: 🛠️fix

#116 🌟(#4) [Fix] 포인트 수정 추가
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl.java
  src/main/java/com/shinhan/soloplay/themecontent/ThemeContentsResponseDTO.java
Labels: 🛠️fix

#117 🌟(#4) 테마 등록 보상 여부 수정
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl.java
Labels: 🛠️fix
