Repository ShinhanT3-CardProject/Backend_repo, pull requests merged in 2024-08, with the labels that each got.

#12 [Feat] 테마 조회 페이지 #8
  src/main/java/com/shinhan/soloplay/auth/AuthController.java
  src/main/java/com/shinhan/soloplay/auth/AuthDTO.java
  src/main/java/com/shinhan/soloplay/auth/AuthEntity.java
  src/main/java/com/shinhan/soloplay/auth/AuthRepository.java
  src/main/java/com/shinhan/soloplay/auth/AuthService.java
  src/main/resources/application.properties
Labels: 🌟feature

#13 [Feat] 레이드, 참가자 엔티티
  pom.xml
  src/main/java/com/shinhan/soloplay/raid/ParticipantEntity.java
  src/main/java/com/shinhan/soloplay/raid/ParticipantId.java
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
  src/main/java/com/shinhan/soloplay/raid/RaidEntity.java
  src/main/java/com/shinhan/soloplay/raid/RaidRepository.java
  src/main/java/com/shinhan/soloplay/raid/RaidService.java
  src/main/java/com/shinhan/soloplay/raid/RaidServiceImpl.java
  src/main/resources/application.properties
Labels: 🌟feature

#17 [Feat] user, merchant entity
  .github/pull_request_template.md
  src/main/java/com/shinhan/soloplay/auth/AuthController.java
  src/main/java/com/shinhan/soloplay/auth/AuthEntity.java
  src/main/java/com/shinhan/soloplay/auth/AuthService.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
Labels: 🌟feature

#24 🌟(#5) [Feat] 유저 패키지 생성 및 비밀번호 변수 변경
  src/main/java/com/shinhan/soloplay/user/UserEntity.java
  src/main/resources/templates/test.html
Labels: 🌟feature

#26 [Fix] ThemeSearchController -> ThemeController 명칭 수정
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
Labels: 🛠️fix

#27 🌟(#3) 테마 엔티티 추가
  src/main/java/com/shinhan/soloplay/SoloplayApplication.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryEntity.java
  src/main/java/com/shinhan/soloplay/theme/SubCategoryEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
Labels: 🌟feature

#28 🌟(#5) [Fix] 가맹점 엔티티 에러 수정
  src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
Labels: 🛠️fix

#29 🌟(#9) [Feat] 레이드 컨트롤러 대미지 계산식 추가
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
  src/main/java/com/shinhan/soloplay/raid/RaidDTO.java
  src/main/java/com/shinhan/soloplay/raid/RaidEntity.java
Labels: 🌟feature

#34 🌟(#6) [Fix]엔티티 수정
  src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
  src/main/java/com/shinhan/soloplay/point/PointEntity.java
Labels: 🛠️fix

#33 🌟(#2) 유저 및 가맹점 리포 및 서비스 제작
  src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantRepository.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantService.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantServiceImpl.java
  src/main/java/com/shinhan/soloplay/point/PointEntity.java
  src/main/java/com/shinhan/soloplay/user/UserEntity.java
  src/main/java/com/shinhan/soloplay/user/UserRepository.java
  src/main/java/com/shinhan/soloplay/user/UserServcieImpl.java
  src/main/java/com/shinhan/soloplay/user/UserService.java
Labels: 🌟feature, 🛠️fix

#35 🌟(#10) [Fix] 전체적으로 자잘한 오류 수정
  src/main/java/com/shinhan/soloplay/card/UserCardEntity.java
  src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantId.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryEntity.java
  src/main/java/com/shinhan/soloplay/theme/SubCategoryEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
Labels: 🛠️fix

#37 [Feat] 레이드 참가 및 결과, 카드사용내역 레포지토리
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryRepository.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantDTO.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantEntity.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantId.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantService.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
Labels: 🌟feature

#38 🌟(#0) [Fix] 가맹점 엔티티 수정
  .github/pull_request_template.md
  .gitignore
  pom.xml
  src/main/java/com/shinhan/soloplay/auth/AuthDTO.java
  src/main/java/com/shinhan/soloplay/auth/AuthService.java
  src/main/java/com/shinhan/soloplay/card/CardEntity.java
  src/main/java/com/shinhan/soloplay/config/SecurityConfig.java
  src/main/java/com/shinhan/soloplay/config/WebConfig.java
  src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantId.java
  src/main/java/com/shinhan/soloplay/point/PointEntity.java
  src/main/java/com/shinhan/soloplay/raid/RaidEntity.java
Labels: 🛠️fix

#39 [Fix] Raid Merchant 관계 일대일에서 일대다로 수정
  src/main/java/com/shinhan/soloplay/raid/RaidEntity.java
Labels: 🛠️fix

#40 [Fix] CouponEntity 중복 칼럼 제거 및 CardUsageHistoryEntity 수정
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryEntity.java
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryRepository.java
  src/main/java/com/shinhan/soloplay/coupon/CouponEntity.java
Labels: 🛠️fix

#42 🌟(#9) [Feat, Fix] 레이드 전투 구현, cardUsageEntity 수정
  .gitignore
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryEntity.java
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryRepository.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantService.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
Labels: 🌟feature, 🛠️fix

#43 🌟(#2) 로그인 및 회원가입 ,Security cors config
  src/main/java/com/shinhan/soloplay/auth/AuthController.java
  src/main/java/com/shinhan/soloplay/auth/AuthDTO.java
  src/main/java/com/shinhan/soloplay/auth/AuthService.java
  src/main/java/com/shinhan/soloplay/config/SecurityConfig.java
  src/main/java/com/shinhan/soloplay/config/WebConfig.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
  src/main/java/com/shinhan/soloplay/user/UserDTO.java
  src/main/java/com/shinhan/soloplay/user/UserEntity.java
Labels: 🌟feature

#47 🌟(#8) [Feat] Theme Entity 4개 단방향 전환 수정 (fetch Lazy, @tostring 추가), Theme 조회관련 기능 일부 구현
  src/main/java/com/shinhan/soloplay/theme/MainCategoryEntity.java
  src/main/java/com/shinhan/soloplay/theme/SubCategoryEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRegisterDTO1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeSearchDTO1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
  src/test/java/com/shinhan/soloplay/ThemeTest.java
Labels: 🌟feature

#50 🌟(#2) [Feat] Swagger 적용
  pom.xml
  src/main/java/com/shinhan/soloplay/user/UserController.java
  src/main/java/com/shinhan/soloplay/user/UserServcieImpl.java
Labels: 🌟feature

#51 🌟(#2) 로그인 회원가입 예외처리
  src/main/java/com/shinhan/soloplay/auth/AuthController.java
  src/main/java/com/shinhan/soloplay/auth/AuthDTO.java
  src/main/java/com/shinhan/soloplay/auth/AuthService.java
  src/main/java/com/shinhan/soloplay/user/UserDTO.java
  src/main/java/com/shinhan/soloplay/user/UserEntity.java
Labels: 🌟feature

#53 🌟(#6 ) [Feat]point CRUD
  src/main/java/com/shinhan/soloplay/coupon/CouponHistoryEntity.java
  src/main/java/com/shinhan/soloplay/point/PointController.java
  src/main/java/com/shinhan/soloplay/point/PointDTO.java
  src/main/java/com/shinhan/soloplay/point/PointEntity.java
  src/main/java/com/shinhan/soloplay/point/PointRepository.java
  src/main/java/com/shinhan/soloplay/point/PointService.java
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
Labels: 🌟feature

#54 🌟(#9) [Fix] Participant 패키지 바뀐 레이드에 맞춰 수정
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryDTO.java
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryRepository.java
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryService.java
  src/main/java/com/shinhan/soloplay/card/CardUsageHistoryServiceImpl.java
  src/main/java/com/shinhan/soloplay/merchant/MerchantRepository.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantDTO.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantEntity.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantId.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantService.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
Labels: 🛠️fix

#55 🌟(#4) 입력받은 버킷리스트를 GPT API로 테마 대분류, 소분류 받기
  src/main/java/com/shinhan/soloplay/theme/BucketListRequestDTO.java
  src/main/java/com/shinhan/soloplay/theme/OpenAIController.java
  src/main/java/com/shinhan/soloplay/theme/OpenAIRequestDTO.java
  src/main/java/com/shinhan/soloplay/theme/OpenAIResponseDTO.java
  src/main/java/com/shinhan/soloplay/theme/OpenAIService.java
  src/main/java/com/shinhan/soloplay/theme/SubCategoryDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeResponseDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
Labels: 🌟feature

#57 🌟(#21 ) coupon 발급, 조회
  src/main/java/com/shinhan/soloplay/coupon/CouponController.java
  src/main/java/com/shinhan/soloplay/coupon/CouponDTO.java
  src/main/java/com/shinhan/soloplay/coupon/CouponHistoryDTO.java
  src/main/java/com/shinhan/soloplay/coupon/CouponHistoryEntity.java
  src/main/java/com/shinhan/soloplay/coupon/CouponHistoryRepository.java
  src/main/java/com/shinhan/soloplay/coupon/CouponIssueRequestDTO.java
  src/main/java/com/shinhan/soloplay/coupon/CouponRepository.java
  src/main/java/com/shinhan/soloplay/coupon/CouponService.java
  src/main/java/com/shinhan/soloplay/coupon/CouponServiceImpl.java
  src/main/java/com/shinhan/soloplay/point/PointController.java
Labels: 🛠️fix

#56 🌟(#9) [Feat] 레이드 배틀 필요 데이터 전송 구현
  src/main/java/com/shinhan/soloplay/participant/ParticipantEntity.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantService.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
  src/main/java/com/shinhan/soloplay/raid/BattleResponseDTO.java
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
Labels: 🌟feature

#60 🌟(#8) [Feat] Theme CRUD를 위한 전반적인 작업 진행
  src/main/java/com/shinhan/soloplay/merchant/MerchantEntity.java
  src/main/java/com/shinhan/soloplay/theme/SubCategoryEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRegisterDTO1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeSearchDTO1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
  src/main/java/com/shinhan/soloplay/user/UserEntity.java
Labels: 🌟feature, 🛠️fix

#63 🌟(#21) coupon 조회, couponId별 재조회
  src/main/java/com/shinhan/soloplay/coupon/CouponController.java
  src/main/java/com/shinhan/soloplay/coupon/CouponRepository.java
  src/main/java/com/shinhan/soloplay/coupon/CouponService.java
  src/main/java/com/shinhan/soloplay/coupon/CouponServiceImpl.java
  src/main/java/com/shinhan/soloplay/coupon/CouponWithDetailsDTO.java
  src/main/java/com/shinhan/soloplay/point/PointController.java
  src/main/java/com/shinhan/soloplay/point/PointService.java
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
Labels: 🌟feature, 🛠️fix

#67 🌟(#16) [Fix] 카드목록
  pom.xml
  src/main/java/com/shinhan/soloplay/card/CardController.java
Labels: 🛠️fix

#68 🌟(#8) [Feat] themeSearch, themeDetail 조회 DB연동 및 FrontEnd 연결 진행
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeSearchDTO1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
Labels: 🌟feature

#65 🌟(#2) 로그인시 세션 수정 ,
  pom.xml
  src/main/java/com/shinhan/soloplay/auth/AuthController.java
  src/main/java/com/shinhan/soloplay/config/SecurityConfig.java
  src/main/java/com/shinhan/soloplay/config/WebConfig.java
Labels: 🛠️fix

#70 🌟(#6) [Fix] 포인트/ 쿠폰 세션 아이디 가져오기
  src/main/java/com/shinhan/soloplay/coupon/CouponController.java
  src/main/java/com/shinhan/soloplay/point/PointController.java
  src/main/java/com/shinhan/soloplay/point/PointService.java
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
Labels: 🛠️fix

#71 🌟(#9) [Fix] 유저 정보 받기 정상화, 레이드 정보 받기
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
Labels: 🛠️fix

#72 🌟(#69) [Fix] 레이드 진행 상태 변경
  src/main/java/com/shinhan/soloplay/raid/RaidController2.java
  src/main/java/com/shinhan/soloplay/raid/RaidDTO.java
  src/main/java/com/shinhan/soloplay/raid/RaidService.java
Labels: 🛠️fix

#73 🌟(#8) [Feat] 나의 테마 상세 구현, 삭제기능 추가, 수정기능 구현 중
  src/main/java/com/shinhan/soloplay/theme/MainCategoryController.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryDTO.java
  src/main/java/com/shinhan/soloplay/theme/SubCategoryDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
Labels: 🌟feature

#74 🌟(#4) [Feat] 테마 등록 백엔드
  src/main/java/com/shinhan/soloplay/theme/MainCategoryController.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryEntity.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/OpenAIService.java
  src/main/java/com/shinhan/soloplay/theme/SubCategoryDTO.java
  src/main/java/com/shinhan/soloplay/theme/SubCategoryRepository.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentRepository.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRegisterDTO1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
Labels: 🌟feature

#75 🌟(#4) [Fix] GPT API 명령어 수정
  src/main/java/com/shinhan/soloplay/theme/OpenAIService.java
Labels: 🛠️fix

#76 🌟(#69 ) [Fix] user정보 session에서 가져오기
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
Labels: 🛠️fix

#78 🌟(#8) [Feat][Fix] MyThemeDetail 수정하기 기능 추가 및 수정
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
Labels: 🌟feature, 🛠️fix

#82 🌟(#9 ) "[Fix] 보상 받기 시 상태 수정 정상화"
  src/main/java/com/shinhan/soloplay/openAI/BucketListRequestDTO.java
  src/main/java/com/shinhan/soloplay/openAI/OpenAIController.java
  src/main/java/com/shinhan/soloplay/openAI/OpenAIRequestDTO.java
  src/main/java/com/shinhan/soloplay/openAI/OpenAIResponseDTO.java
  src/main/java/com/shinhan/soloplay/openAI/OpenAIService.java
  src/main/java/com/shinhan/soloplay/openAI/ThemeResponseDTO.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantRepository.java
  src/main/java/com/shinhan/soloplay/participant/ParticipantServiceImpl.java
  src/main/java/com/shinhan/soloplay/raid/BattleResponseDTO.java
  src/main/java/com/shinhan/soloplay/raid/RaidController.java
  src/main/java/com/shinhan/soloplay/raid/RaidController2.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentRepository.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentRepositoryJS.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRegisterDTO1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImplJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
Labels: 🛠️fix

#84 [Feat] 테마 달성 시 쿠폰 발급
  src/main/java/com/shinhan/soloplay/coupon/CouponController.java
  src/main/java/com/shinhan/soloplay/coupon/CouponIssueRequestDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentRepositoryJS.java
  src/main/java/com/shinhan/soloplay/theme/ThemeEntity.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
Labels: 🌟feature

#86 🌟(#4) [Fix] 정책 기능 수정 중
  src/main/java/com/shinhan/soloplay/openAI/OpenAIController.java
  src/main/java/com/shinhan/soloplay/theme/MainCategoryController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeControllerJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepository1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImplJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
Labels: 🛠️fix

#87 🌟(#4) [Fix] 정책 중 오류 수정
  src/main/java/com/shinhan/soloplay/theme/ThemeControllerJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImplJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
Labels: 🐞bugfix

#89 🌟(#4) 정책 수정
  src/main/java/com/shinhan/soloplay/config/SecurityConfig.java
  src/main/java/com/shinhan/soloplay/theme/ThemeContentsResponseDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeControllerJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeDetailResponseDTO.java
  src/main/java/com/shinhan/soloplay/theme/ThemeRepositoryJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImplJK.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceJK.java
Labels: 🛠️fix

#90 🌟(#8) [Fix] themeController, themeServiceImpl 일부 수정 (Entity -> DTO 전송방식 변경)
  src/main/java/com/shinhan/soloplay/theme/ThemeController.java
  src/main/java/com/shinhan/soloplay/theme/ThemeService1.java
  src/main/java/com/shinhan/soloplay/theme/ThemeServiceImpl1.java
Labels: 🛠️fix

#91 🌟(#6 ) 포인트 계산 조건 변경, 카테고리별 총합, 비율 계산
  src/main/java/com/shinhan/soloplay/point/PointController.java
  src/main/java/com/shinhan/soloplay/point/PointService.java
  src/main/java/com/shinhan/soloplay/point/PointServiceImpl.java
Labels: 🌟feature, 🛠️fix
